{% set name = "harmony-py" %}
{% set version = "0.4.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/harmony-py-{{ version }}.tar.gz
  sha256: 735b1410306110e6a0e76c305db98730d0060389fdc9e8403d2e4b0049143355

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.8
    - python-dateutil >=2.8.2,<2.9.dev0
    - python-dotenv >=0.20.0,<0.21.dev0
    - progressbar2 >=4.2.0,<4.3.dev0
    - requests >=2.28,<3.dev0
    - sphinxcontrib-napoleon >=0.7,<1.dev0
    - curlify >=2.2.1,<2.3.dev0

test:
  imports:
    - harmony
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nasa/harmony-py
  summary: The NASA Harmony Python library
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://harmony.earthdata.nasa.gov/

extra:
  recipe-maintainers:
    - jhkennedy
    - betolink
    - owenlittlejohns
