{% set name = "harmony-py" %}
{% set version = "1.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e20bb8e173fdfe14022783e42d78b350d7bf003b2c9a8ce9bcde584bc9a78842

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - python-build
  run:
    - python >={{ python_min }}
    - python-dateutil >=2.9
    - python-dotenv >=1.1.0
    - progressbar2 >=4.2.0
    - requests >=2.32.3
    - curlify >=2.2.1
    - shapely >=2.1.2

test:
  imports:
    - harmony
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/nasa/harmony-py
  summary: The NASA Harmony Python library
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://harmony.earthdata.nasa.gov/

extra:
  recipe-maintainers:
    - jhkennedy
    - betolink
    - owenlittlejohns
