{% set name = "harmony-py" %}
{% set version = "0.6.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cf49dee5939c985513604f98a6a6a5426f6e999e3450454db6377615782d786b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - python-build
  run:
    - python >={{ python_min }}
    # Harmony pins to "compatible releases" (~= X.Y.Z) which is equivalent to >= X.Y.Z, == Z.Y.* for pip
    # or >=X.Y.Z,=X.Y for conda; see:
    # - https://peps.python.org/pep-0440/#compatible-release
    # - https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#package-match-specifications
    - python-dateutil >=2.8.2,<2.9.dev0
    - python-dotenv >=0.20.0,<0.21.dev0
    - progressbar2 >=4.2.0,<4.3.dev0
    - requests >=2.32.3,<2.33.dev0
    - sphinxcontrib-napoleon >=0.7,<1.dev0
    - curlify >=2.2.1,<2.3.dev0
    - shapely >=2.0.4,<2.1.dev0

test:
  imports:
    - harmony
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/nasa/harmony-py
  summary: The NASA Harmony Python library
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://harmony.earthdata.nasa.gov/

extra:
  recipe-maintainers:
    - jhkennedy
    - betolink
    - owenlittlejohns
