{% set name = "harmony-py" %}
{% set version = "0.5.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b11a919f896ec7878a3f20f35826b597c48742f812de93e178629d2664ac8030

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - python-build
  run:
    - python >={{ python_min }}
    # Harmony pins to "compatible releases" (~= X.Y.Z) which is equivalent to >= X.Y.Z, == Z.Y.* for pip
    # or >=X.Y.Z,=X.Y for conda; see:
    # - https://peps.python.org/pep-0440/#compatible-release
    # - https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#package-match-specifications
    - python-dateutil >=2.8.2,=2.8
    - python-dotenv >=0.20.0,=0.20
    - progressbar2 >=4.2.0,=4.2
    - requests >=2.32.3,=2.32
    - sphinxcontrib-napoleon >=0.7,=0
    - curlify >=2.2.1,=2.2
    - shapely >=2.0.4,=2.0

test:
  imports:
    - harmony
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/nasa/harmony-py
  summary: The NASA Harmony Python library
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://harmony.earthdata.nasa.gov/

extra:
  recipe-maintainers:
    - jhkennedy
    - betolink
    - owenlittlejohns
