{% set name = "harmony-py" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e7bcf2891afdca0fa14dbbbf3a5e0139a2cbc84348e575e706f25ffb61749564

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
    - setuptools_scm >=8
    - python-build
  run:
    - python >={{ python_min }}
    - python-dateutil >=2.9
    - python-dotenv >=1.1.0
    - progressbar2 >=4.2.0
    - requests >=2.32.3
    - curlify >=2.2.1
    - shapely >=2.1.2

test:
  imports:
    - harmony
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/nasa/harmony-py
  summary: The NASA Harmony Python library
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://harmony.earthdata.nasa.gov/

extra:
  recipe-maintainers:
    - jhkennedy
    - betolink
    - owenlittlejohns
